use super::entrance::{BuildingEntrance, EntranceCandidate, EntranceSide};

#[derive(Debug, Clone, Copy)]
pub struct EntranceEvidence {
    pub north_road: bool,
    pub south_road: bool,
    pub east_road: bool,
    pub west_road: bool,
    pub north_footway: bool,
    pub south_footway: bool,
    pub east_footway: bool,
    pub west_footway: bool,
    pub north_parking: bool,
    pub south_parking: bool,
    pub east_parking: bool,
    pub west_parking: bool,
    pub north_entrance_poi: bool,
    pub south_entrance_poi: bool,
    pub east_entrance_poi: bool,
    pub west_entrance_poi: bool,
}

impl EntranceEvidence {
    pub fn empty() -> Self {
        Self {
            north_road: false,
            south_road: false,
            east_road: false,
            west_road: false,
            north_footway: false,
            south_footway: false,
            east_footway: false,
            west_footway: false,
            north_parking: false,
            south_parking: false,
            east_parking: false,
            west_parking: false,
            north_entrance_poi: false,
            south_entrance_poi: false,
            east_entrance_poi: false,
            west_entrance_poi: false,
        }
    }
}

impl EntranceEvidence {}

/// Detect a real mapped entrance/door node from OSM / Overture data.
///
/// The node must already be part of the building outline's processed nodes.
/// This preserves the exact Minecraft coordinate generated by the parser.
pub fn detect_mapped_entrance(
    nodes: &[crate::osm_parser::ProcessedNode],
    min_x: i32,
    min_z: i32,
    max_x: i32,
    max_z: i32,
) -> Option<EntranceCandidate> {
    let center_x = (min_x + max_x) / 2;
    let center_z = (min_z + max_z) / 2;

    nodes
        .iter()
        .filter(|node| {
            node.tags.contains_key("entrance")
                || node.tags.contains_key("door")
        })
        .map(|node| {
            let north = (node.z - min_z).abs();
            let south = (node.z - max_z).abs();
            let west = (node.x - min_x).abs();
            let east = (node.x - max_x).abs();

            let (side, wall_distance, center_distance) = {
                let distances = [
                    (EntranceSide::North, north, (node.x - center_x).abs()),
                    (EntranceSide::South, south, (node.x - center_x).abs()),
                    (EntranceSide::West, west, (node.z - center_z).abs()),
                    (EntranceSide::East, east, (node.z - center_z).abs()),
                ];

                distances
                    .into_iter()
                    .min_by_key(|(_, wall_distance, _)| *wall_distance)
                    .unwrap()
            };

            let mut candidate = EntranceCandidate::new(side, node.x, node.z);

            let has_entrance = node.tags.contains_key("entrance");
            let has_door = node.tags.contains_key("door");

            candidate.has_entrance_poi = has_entrance;

            // Explicit mapped entrance is the strongest mapped evidence.
            if has_entrance {
                candidate.score += 100.0;
            } else if has_door {
                // A mapped door is still strong evidence, but weaker
                // than an explicit entrance= node.
                candidate.score += 50.0;
            }

            // Prefer nodes that are actually on the reconstructed
            // exterior wall. Interior nodes tagged as doors/entrances
            // must not outrank a real exterior entrance.
            if wall_distance == 0 {
                candidate.score += 25.0;
            } else {
                // Keep the candidate available as mapped evidence,
                // but penalize nodes that are not exactly on the wall.
                candidate.score -= (wall_distance.min(10) as f32) * 5.0;
            }

            // Small deterministic tie-break preference toward the
            // geometric center of the corresponding exterior wall.
            // This is ONLY a tie-breaker; it never outranks stronger
            // entrance/door evidence.
            candidate.score -= (center_distance as f32) * 0.01;

            (candidate, wall_distance)
        })
        .filter(|(_, wall_distance)| *wall_distance == 0)
        .max_by(|(a, _), (b, _)| {
            a.score
                .partial_cmp(&b.score)
                .unwrap_or(std::cmp::Ordering::Equal)
        })
        .map(|(candidate, _)| candidate)
}

pub fn detect_main_entrance(
    min_x: i32,
    min_z: i32,
    max_x: i32,
    max_z: i32,
    evidence: EntranceEvidence,
) -> Option<BuildingEntrance> {
    let center_x = (min_x + max_x) / 2;
    let center_z = (min_z + max_z) / 2;

    let mut candidates = vec![
        EntranceCandidate::new(EntranceSide::North, center_x, min_z),
        EntranceCandidate::new(EntranceSide::South, center_x, max_z),
        EntranceCandidate::new(EntranceSide::West, min_x, center_z),
        EntranceCandidate::new(EntranceSide::East, max_x, center_z),
    ];

    candidates[0].has_road = evidence.north_road;
    candidates[0].has_footway = evidence.north_footway;
    candidates[0].has_parking = evidence.north_parking;
    candidates[0].has_entrance_poi = evidence.north_entrance_poi;

    candidates[1].has_road = evidence.south_road;
    candidates[1].has_footway = evidence.south_footway;
    candidates[1].has_parking = evidence.south_parking;
    candidates[1].has_entrance_poi = evidence.south_entrance_poi;

    candidates[2].has_road = evidence.west_road;
    candidates[2].has_footway = evidence.west_footway;
    candidates[2].has_parking = evidence.west_parking;
    candidates[2].has_entrance_poi = evidence.west_entrance_poi;

    candidates[3].has_road = evidence.east_road;
    candidates[3].has_footway = evidence.east_footway;
    candidates[3].has_parking = evidence.east_parking;
    candidates[3].has_entrance_poi = evidence.east_entrance_poi;

    for candidate in &mut candidates {
        candidate.calculate_score();
    }

    candidates
        .into_iter()
        .filter(|candidate| {
            candidate.has_road
                || candidate.has_footway
                || candidate.has_parking
                || candidate.has_entrance_poi
        })
        .max_by(|a, b| {
            a.score
                .partial_cmp(&b.score)
                .unwrap_or(std::cmp::Ordering::Equal)
        })
        .map(BuildingEntrance::from_candidate)
}
